image: Visual Studio 2017

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

on_success:
  - cmd: dotnet pack -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - ps: Push-AppveyorArtifact "stfservice-net\bin\Release\stfservice-net.1.0.0-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"
